dump978:
dump978 gets UAT data from the SDR
    image: ghcr.io/sdr-enthusiasts/docker-dump978:latest
profiles:

    donotstart

    tty: true
    container_name: dump978
    hostname: dump978
    restart: always
    labels:
      

    "autoheal=true"
      device_cgroup_rules:
        'c 189:* rwm'
        environment:
            TZ=${FEEDER_TZ}
                LAT=${FEEDER_LAT}
                LON=${FEEDER_LONG}
                DUMP978_RTLSDR_DEVICE=${UAT_SDR_SERIAL}
                DUMP978_SDR_GAIN=${UAT_SDR_GAIN}
               
        volumes:
            /opt/adsb/dump978:/var/globe_history
                /dev:/dev:ro
        tmpfs:
            /run:exec,size=64M
                /tmp:size=64M
                /var/log:size=32M

TAR1090 (Map Web Page) parameters:
    

    UPDATE_TAR1090=true
      
        TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
        TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
        TAR1090_MESSAGERATEINTITLE=true
            
        TAR1090_PLANECOUNTINTITLE=true
        TAR1090_ENABLE_AC_DB=true
        TAR1090_SITESHOW=true
        TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
        TAR1090_RANGE_OUTLINE_WIDTH=2.0
        TAR1090_RANGERINGSDISTANCES=50,100,150,200
        TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
        TAR1090_USEROUTEAPI=true
